### ISSUE TITLE
OID AS INTERLIS.UUIDOID fehlt in Derivatmodell

### ISSUE THREAD

**Issue by edigonzales** [claeis/ilishaper#1]
Das Basismodell ist wie folgt definiert:

```
  TOPIC Bienenstandorte =
    OID AS INTERLIS.UUIDOID;
```

Das resultierende Derivatmodell nur noch:

```
  TOPIC Bienenstandorte =
```

Befehl:
```
java -jar ilishaper-1.0.1.jar --createModel --config bienenstandorte.ini --modeldir ".;https://models.geo.admin.ch/" --out SO_ALW_Bienenstandorte_20241113.ili SO_ALW_Bienenstandorte_restricted_20241113.ili
```

Also Folge davon weist auch das resultierende XTF _keine_ UUID als TID auf.

Daten, Modelle und Konfig im Anhang.
[Archive.zip](https://github.com/user-attachments/files/17750355/Archive.zip)

**Comment by claeis** [comment]
Das ist so Absicht. Der ilishaper kann (ohne persistente Abbildungstabelle) keine _stabilen_ TIDs/BIDs erzeugen.

**Comment by edigonzales** [comment]
Verständnisfrage: Warum reicht es nicht die bestehenden OID einfach zu übernehmen. Es entstehen ja keine zusätzlichen Objekte.

**Comment by claeis** [comment]
Ja doch, es entstehen neue technische Objekte (die dieselbe Realität abbilden). Es wäre technisch falsch, dieselben OIDs zu verwenden. Weil es andere Objekte sind, wäre die OID nicht mehr eindeutig.

**Comment by edigonzales** [comment]
Mmmh, ja stimmt.

**Comment by beistehen** [comment]
> Mmmh, ja stimmt.

Wird mir auch gerade bewusst. Das Wort *stabil* ist schon noch entscheidend...

**Comment by cymed** [comment]
@claeis Der Modellierungsansatz gilt jedoch nur dann, wenn effektiv ein neues Datenmodell generiert wird. Werden ganze Klassen eliminiert, ändern sich die technischen Objekte auch nicht.

Beispielnutzung: Elimination zweier Klassen aus einem xtf, die in einem 2. Schritt nicht importiert werden sollen

```
[DSS_2020_1_LV95]
name=DSS_2020_1_LV95
issuer=http://www.vsa.ch/models
version=18.10.2023


[DSS_2020_1_LV95.Siedlungsentwaesserung.Abwasserbauwerk_Text]
ignore=true

[DSS_2020_1_LV95.Siedlungsentwaesserung.Haltung_Text]
ignore=true
```

Wird nun mit` java -jar ilishaper-1.0.1.jar --deriveData --config strip_texts.ini --modeldir ".;http://www.vsa.ch/models" --out DSS_noTexts.xtf DSS.xtf ` das ini auf ein xtf appliziert, entstehen keine neuen technischen Objekte.

PS: Bedeutet dies im Umkehrschluss, dass im auch neue Primärschlüssel generiert werden müssten, wenn Klasse `A` in Modell `B` die Klasse `C `in Modell `D` `EXTENDS `und `D.C` eine OID hat?

**Comment by sjib** [comment]
Theoretisch mag die Argumenation von @claeis stimmen, ilishaper ist im Alltag so nicht brauchbar, wenn die OID nicht übernommen wird. 
Wenn ich nur einzelne Attribute von Objekten will und ilishaper nutze, um diese rauszufiltern, dann brauche ich die Infos zur OID sonst kann ich das nirgends mehr integrieren oder verknüpfen. 

Mindestens als Option sollte das möglich sein.

**Comment by beistehen** [comment]
Wenn man aus einem bestehenden Modell Klassen entfernt, so ist das gemäss Change-Management-Regeln ein neues Modell und erhält einen neuen Modellnamen.
Will man aus einem Datensatz Objekte entfernen, so muss man ein anderes Tool wie z. B. ili2db verwenden, da ist ilishaper wohl nicht das richtige Werkzeug.

**Comment by sjib** [comment]
Ich möchte eine Option, dass ich die OID ins abgespeckte  Modell mitnehmen kann.

**Comment by sjib** [comment]
Bei LKMap wird auch die Objekt-Id aus dem WI Modell übernommen
