### ISSUE TITLE
Definition Basismodell in ini

### ISSUE THREAD

**Issue by sjib** [claeis/ilishaper#3]
Wie definiert man das[Basismodell] korrekt?

![grafik](https://github.com/user-attachments/assets/f4d00c20-4526-4a0b-9b48-4c5bbd081bbf)

Ich habe auch schon ausprobiert:
[Basismodell]
name="DSS_2015_LV95"
version=31.10.2023

Gibt dieselbe Fehlermeldung.

**Comment by sjib** [comment]
Aufruf den ich verwende:
`
java -jar ilishaper-1.0.1.jar --modeldir %ITF_DIR;%JAR_DIR/ilimodels; --deriveData --config myselectiondss.ini --out Derivatdaten.xtf transferdatensatz_2015_d_LV95_T-20241022_with_ARCS.xtf`

**Comment by beistehen** [comment]
`[Basismodell]` ist ein Platzhalter.

In deinem Fall muss es heissen `[DSS_2015_LV95]`

Siehe auch den [LinkedIn-Post](https://www.linkedin.com/pulse/interlis-leicht-gemacht-44-ilishaper-shape-your-xtf-stefan-ziegler-cxohe/) von @edigonzales als Beispiel.

**Comment by beistehen** [comment]
Doku wurde vor wenigen Stunden diesbezüglich bereits präzisiert, siehe [Änderung](https://github.com/claeis/ilishaper/commit/d35f26878282bdde3cd91c5de3dd53a3aafea222) resp. [aktuelle Doku](https://github.com/claeis/ilishaper/blob/main/docs/ilishaper.rst). 👍

**Comment by sjib** [comment]
@claeis @beistehen Danke für die Ergänzungen - jetzt habe ich es geschafft. Ich habe mich verwirren lassen, dass im Beispiel von @edigonzales das Ursprungsmodell *_restricted heisst.
