### ISSUE TITLE
Umgang mit Filteroptionen

### ISSUE THREAD

**Issue by cymed** [claeis/ilishaper#4]
Kann aktuell nur nach einem Attribut gefiltert werden oder wird die Verwendung mehrerer Zielwerte unterstützt

Pseudocodes
```
[Model.Topic.Object]
filter=OR("Hierarchie==#extrem_wichtig,#ebenfalls_wichtig") AND "status=#aktiv" 
```

Die Kirsche auf der Torte wäre es, auch Pendants zu LIKE / IN in sql oder sogar regex-Filter zu Verfügung zu haben

**Comment by beistehen** [comment]
Die [Doku](https://github.com/claeis/ilishaper/blob/main/docs/ilishaper.rst#ini-konfigurationsdatei) sagt bezüglich `filter`:
> Ein Ausdruck (Syntax-Regel Expression; wie bei einem Mandatory-Constraint).

sowie

> Der Ausdruck muss pro Objekt (ohne Beizug anderer Objekte) auswertbar sein (darf also keine Rollen oder Referenzattribute enthalten).

Somit also grundsätzlich vieles gemäss [Referenzhandbuch](https://geostandards-ch.github.io/doc_refhb24/#2_13_C1) 🥳

Falls _Funktionen_ bereits von der aktuellen Software-Version (v1.0.1) unterstützt werden sollten (@claeis ?), könntest du für RegExp die Funktion `Text.matches(val: TEXT; regex: TEXT): BOOLEAN;` verwenden.

**Comment by claeis** [comment]
Eingebaute Funktionen gehen (also auch Text), Funktionen via Plugins noch nicht (#5)

**Comment by edigonzales** [comment]
@claeis Das Basismodell muss aber das Funktionsmodell importieren, oder?

```
[SO_ALW_Bienenstandorte_restricted_20241113.Bienenstandorte.Bienenstandort]
filter="Text.startsWith(Nummer, \"12\")"
```

funktioniert nicht out-of-the-box. Wenn ich im Basismodell `IMPORTS Text;` hinzufüge, geht es.
